### ISSUE TITLE
Effect performance

### ISSUE THREAD

**Issue by another-sapiens** [KaeruCT/Go-To-Sleep-Android#2]
Hi!
The in-app gameplay is working perfectly, save for small hiccups when the blur effect shows up. The same can be seen in the Start menu (minus the blur).

It could be down to device performance, though. 
Some effects are heavier on low-end devices – maybe an option to toggle them could help?

**Comment by KaeruCT** [comment]
Thanks for your suggestion. There's an option in the start screen to do this now (added in version 1.1)
