### ISSUE TITLE
"Back to start" link is selectable

### ISSUE THREAD

**Issue by f512** [KaeruCT/Go-To-Sleep-Android#3]
When I tap on screen, after a while, the link is selected.

![Screenshot_20210704-152728_Go_To_Sleep](https://user-images.githubusercontent.com/56228172/124387107-88723000-dcdd-11eb-9170-817e5919b166.png)

**Comment by KaeruCT** [comment]
This should be fixed from version 1.1 onwards. Thanks for reporting!
