### ISSUE TITLE
Multiple instances of the game on top of the other

### ISSUE THREAD

**Issue by f512** [KaeruCT/Go-To-Sleep-Android#4]
When I tap on "Back to start", then "Start the game", then "Back to start" again, etc.
Multiple instances of the game are overlapping (soooo many sheep to be counted lol)

![Screenshot_20210704-152543_Go_To_Sleep](https://user-images.githubusercontent.com/56228172/124387182-d25b1600-dcdd-11eb-9b4a-10ebfe39d48e.png)

**Comment by KaeruCT** [comment]
Thanks for the report. This should be fixed from version 1.1 onwards
