### ISSUE TITLE
Blurry screen 

### ISSUE THREAD

**Issue by f512** [KaeruCT/Go-To-Sleep-Android#5]
Not sure if it's a feature or a bug, but sometime, the screen is blurry.

![Screenshot_20210704-152614_Go_To_Sleep](https://user-images.githubusercontent.com/56228172/124387229-fd456a00-dcdd-11eb-959d-02f0ca16f4f9.png)

Also sometime the screen is in negative colors.

Thanks !

**Comment by another-sapiens** [comment]
I believe these are intended effects, sort of showing that we're "falling asleep".  :)

**Comment by KaeruCT** [comment]
It's not a bug. But you can disable these effects from the title screen (from version 1.1 onwards)
